x-uffizzi:
  ingress:
    service: nginx
    port: 8081
  continuous_previews:
    deploy_preview_when_pull_request_is_opened: true
    delete_preview_when_pull_request_is_closed: true
    share_to_github: true

services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - ./uffizzi/nginx:/etc/nginx/conf.d/

  app:
    depends_on:
      - "postgres"
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 3001:3001

  postgres:
    image: postgres:14-alpine
    user: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres" # See https://docs.uffizzi.com/guides/secrets/#add-secrets-element-to-your-docker-compose-template
    deploy:
      resources:
        limits:
          memory: 500M
